//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drone_Proyect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medication
    {
        public long id_Med { get; set; }
        public string name { get; set; }
        public Nullable<double> weigth { get; set; }
        public string code { get; set; }
        public string image { get; set; }
    }
}
